version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .:/postgres-source
      - postgres-build:/postgres-source/build
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
  postgres-build:
   

